apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-app-vs
spec:
  hosts:
  - my-app.com
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - name: "my-app"
    route:
    - destination:
        host: my-app-service.default.svc.cluster.local
        port:
          number: 80
    retries:
      attempts: 5
      perTryTimeout: 120s
